### ISSUE TITLE
Question: Join

### ISSUE THREAD

**Issue by xItzDiamondx** [Scratch-Snippets/scratch-snippets.github.io#1]
can I join

**Comment by xItzDiamondx** [comment]
cc @brourbeinsus

**Comment by xItzDiamondx** [comment]
If not I'll just be a collaborator

**Comment by brourbeinsus** [comment]
I’ll let you know when I’m ready, as I’m just setting up the website.

**Comment by xItzDiamondx** [comment]
Great, I'm really good at HTML though.

**Comment by xItzDiamondx** [comment]
Oh, and please add @NotDiamondZ to it not me.
