### ISSUE TITLE
Add contrib

### ISSUE THREAD

**Issue by brourbeinsus** [Scratch-Snippets/scratch-snippets.github.io#8]
Ok this is the issue where I add contributors :)

**Comment by brourbeinsus** [comment]
@all-contributors please add @brourbeinsus for head developer

**Comment by brourbeinsus** [comment]
@all-contributors please add @brourbeinsus for projectManagement

**Comment by brourbeinsus** [comment]
@all-contributors please add @brourbeinsus for ideas

**Comment by brourbeinsus** [comment]
@all-contributors please add @ShadowbreakerGD for projectManagement

**Comment by brourbeinsus** [comment]
@all-contributors please add @ShadowbreakerGD for ideas

**Comment by brourbeinsus** [comment]
@all-contributors please add @ShadowbreakerGD for ideas

**Comment by brourbeinsus** [comment]
@all-contributors please add @brourbeinsus for ideas, projectmanagement

**Comment by brourbeinsus** [comment]
@all-contributors please add @brourbeinsus for ideas, projectmanagement

**Comment by brourbeinsus** [comment]
@all-contributors please add @ShadowbreakerGD for tests and code

**Comment by brourbeinsus** [comment]
@all-contributors please add @brourbeinsus for ideas

**Comment by brourbeinsus** [comment]
@all-contributors please add @ShadowbreakerGD for ideas

**Comment by brourbeinsus** [comment]
@all-contributors please add @brourbeinsus for ideas

**Comment by brourbeinsus** [comment]
@all-contributors please add @ShadowbreakerGD for ideas

**Comment by brourbeinsus** [comment]
@all-contributors please add @NotDiamondZ for ideas

**Comment by brourbeinsus** [comment]
@all-contributors please add @brourbeinsus for projectManagement

**Comment by brourbeinsus** [comment]
@all-contributors please add @brourbeinsus for content

**Comment by brourbeinsus** [comment]
@all-contributors please add @ShadowbreakerGD for content

**Comment by brourbeinsus** [comment]
hey @all-contributors let’s add @brourbeinsus and @ShadowbreakerGD for maintenance

**Comment by brourbeinsus** [comment]
@all-contributors add @ShadowbreakerGD for maintenance as well

**Comment by NotDiamondZ** [comment]
@brourbeinsus I think that it should be a discussion instead

**Comment by brourbeinsus** [comment]
@NotDiamondZ I think your right, it does look pretty sus as an issue

**Comment by NotDiamondZ** [comment]
lol

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
